version: "3"

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always 
    volumes:
      - ./odoo-db:/var/lib/postgresql/data 

  odoo:
    container_name: odoo
    image: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    tty: true
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - ./odoo_data:/var/lib/data
    restart: always
